Bipum-In/Bipum-In-BE

src/main/java/com/sparta/bipuminbe/common/entity/Department.java
src/main/java/com/sparta/bipuminbe/common/entity/ReturnRequest.java
src/main/java/com/sparta/bipuminbe/common/exception/ErrorCode.java
src/main/java/com/sparta/bipuminbe/department/controller/DepartmentController.java
src/main/java/com/sparta/bipuminbe/department/dto/DepartmentDto.java
src/main/java/com/sparta/bipuminbe/department/repository/DepartmentRepository.java
src/main/java/com/sparta/bipuminbe/department/service/DepartmentService.java

feat. Department CRUD 완료.

---

src/main/java/com/sparta/bipuminbe/category/controller/CategoryController.java
src/main/java/com/sparta/bipuminbe/category/dto/CategoryDto.java
src/main/java/com/sparta/bipuminbe/category/repository/CategoryRepository.java
src/main/java/com/sparta/bipuminbe/category/service/CategoryService.java
src/main/java/com/sparta/bipuminbe/common/entity/Category.java

feat, Category CRUD categoryName 중복 체크 메서드 추가.

feat, Category CRUD categoryName 중복 체크 메서드 추가.

---

src/main/java/com/sparta/bipuminbe/common/entity/Department.java
src/main/java/com/sparta/bipuminbe/common/entity/Partners.java
src/main/java/com/sparta/bipuminbe/common/exception/ErrorCode.java
src/main/java/com/sparta/bipuminbe/partners/controller/PartnersController.java
src/main/java/com/sparta/bipuminbe/partners/dto/PartnersDto.java
src/main/java/com/sparta/bipuminbe/partners/repository/PartnersRepository.java
src/main/java/com/sparta/bipuminbe/partners/service/PartnersService.java

feat. Partners CRUD 완료.

---

src/main/java/com/sparta/bipuminbe/common/enums/RequestType.java
src/main/java/com/sparta/bipuminbe/requests/controller/RequestsController.java
src/main/java/com/sparta/bipuminbe/requests/dto/RequestsResponseDto.java
src/main/java/com/sparta/bipuminbe/requests/service/RequestsService.java

feat : AdminRequests List 구현 중간 저장.

feat : AdminRequests List 구현 중간 저장.

---

src/main/java/com/sparta/bipuminbe/partners/controller/PartnersController.java
src/main/java/com/sparta/bipuminbe/requests/controller/RequestsController.java
src/main/java/com/sparta/bipuminbe/requests/dto/RequestsResponseDto.java

fix : PartnersController Mapping 오류 수정.

fix : PartnersController Mapping 오류 수정.

---

src/main/java/com/sparta/bipuminbe/requests/controller/RequestsController.java
src/main/java/com/sparta/bipuminbe/requests/repository/RequestsRepository.java
src/main/java/com/sparta/bipuminbe/requests/service/RequestsService.java

fix: Admin Requests 페이지 수리중도 처리전에 포함되도록 설정.

fix: Admin Requests 페이지 수리중도 처리전에 포함되도록 설정.

---

src/main/java/com/sparta/bipuminbe/common/exception/ErrorCode.java
src/main/java/com/sparta/bipuminbe/requests/controller/RequestsController.java
src/main/java/com/sparta/bipuminbe/requests/controller/SupplyRequestController.java
src/main/java/com/sparta/bipuminbe/requests/dto/SupplyRequestResponseDto.java
src/main/java/com/sparta/bipuminbe/requests/service/RequestsService.java
src/main/java/com/sparta/bipuminbe/requests/service/SupplyRequestService.java

feat: Admin Requests Supply Details 페이지 구현

feat: Admin Requests Supply Details 페이지 구현

---

src/main/java/com/sparta/bipuminbe/requests/controller/RequestsController.java
src/main/java/com/sparta/bipuminbe/requests/service/RequestsService.java

fix: Admin Requests 조회 RequestParam 방식 변경

fix: Admin Requests 조회 RequestParam 방식 변경

---

src/main/java/com/sparta/bipuminbe/requests/controller/RequestsController.java
src/main/java/com/sparta/bipuminbe/requests/service/RequestsService.java

fix: Admin Requests List RequestParam Status ALL 추가.

fix: Admin Requests List RequestParam Status ALL 추가.

---

src/main/java/com/sparta/bipuminbe/requests/controller/ReturnRequestController.java
src/main/java/com/sparta/bipuminbe/requests/dto/ReturnRequestResponseDto.java
src/main/java/com/sparta/bipuminbe/requests/service/RepairRequestService.java
src/main/java/com/sparta/bipuminbe/requests/service/ReturnRequestService.java
src/main/java/com/sparta/bipuminbe/requests/service/SupplyRequestService.java

feat: Admin Requests Return Details 페이지 완성.

feat: Admin Requests Return Details 페이지 완성.

---

src/main/java/com/sparta/bipuminbe/requests/controller/RequestsController.java
src/main/java/com/sparta/bipuminbe/user/controller/UserController.java
src/main/java/com/sparta/bipuminbe/user/dto/UserResponseDto.java
src/main/java/com/sparta/bipuminbe/user/repository/UserRepository.java
src/main/java/com/sparta/bipuminbe/user/service/UserService.java

feat: 부서별 유저 리스트 구현.

---

src/main/java/com/sparta/bipuminbe/common/entity/Supply.java
src/main/java/com/sparta/bipuminbe/common/enums/RequestStatus.java
src/main/java/com/sparta/bipuminbe/requests/controller/RequestsController.java
src/main/java/com/sparta/bipuminbe/requests/controller/SupplyRequestController.java
src/main/java/com/sparta/bipuminbe/requests/service/SupplyRequestService.java
src/main/java/com/sparta/bipuminbe/supply/service/SupplyService.java

feat: 비품 요청 승인/거부 구현 완료.

---

src/main/java/com/sparta/bipuminbe/requests/controller/ReturnRequestController.java
src/main/java/com/sparta/bipuminbe/requests/service/ReturnRequestService.java

feat: Requests Return Details 승인/거부 구현

feat: Requests Return Details 승인/거부 구현

---

src/main/java/com/sparta/bipuminbe/common/entity/Supply.java
src/main/java/com/sparta/bipuminbe/requests/controller/RepairRequestController.java
src/main/java/com/sparta/bipuminbe/requests/service/RepairRequestService.java
src/main/java/com/sparta/bipuminbe/requests/service/SupplyRequestService.java

feat: 수리 요청 승인/거절 기능 구현.

---

src/main/java/com/sparta/bipuminbe/common/exception/ErrorCode.java
src/main/java/com/sparta/bipuminbe/supply/controller/SupplyController.java
src/main/java/com/sparta/bipuminbe/supply/dto/SupplyUserDto.java
src/main/java/com/sparta/bipuminbe/supply/repository/SupplyRepository.java
src/main/java/com/sparta/bipuminbe/supply/service/SupplyService.java

feat : 비품목록 셀렉트박스 구현

---

src/main/java/com/sparta/bipuminbe/common/entity/Supply.java
src/main/java/com/sparta/bipuminbe/supply/controller/SupplyController.java
src/main/java/com/sparta/bipuminbe/supply/dto/SupplyDetailResponseDto.java
src/main/java/com/sparta/bipuminbe/supply/dto/SupplyRequestDto.java
src/main/java/com/sparta/bipuminbe/supply/dto/SupplyResponseDto.java
src/main/java/com/sparta/bipuminbe/supply/repository/SupplyRepository.java
src/main/java/com/sparta/bipuminbe/supply/service/SupplyService.java

fix :  비품 일부 반영

---

src/main/java/com/sparta/bipuminbe/requests/controller/RequestsController.java
src/main/java/com/sparta/bipuminbe/supply/service/SupplyService.java

fix: 비품 수정 권한 수정.

---

src/main/java/com/sparta/bipuminbe/supply/controller/SupplyController.java
src/main/java/com/sparta/bipuminbe/supply/repository/SupplyRepository.java
src/main/java/com/sparta/bipuminbe/supply/service/SupplyService.java

fix : 비품등록, 비품삭제 비품목록 셀렉트박스 오류 수정

fix : 비품등록, 비품삭제 비품목록 셀렉트박스 오류 수정

---

src/main/java/com/sparta/bipuminbe/supply/controller/SupplyController.java
src/main/java/com/sparta/bipuminbe/supply/dto/SupplyCategoryDto.java
src/main/java/com/sparta/bipuminbe/supply/service/SupplyService.java

fix : 비품조회 수정

---

src/main/java/com/sparta/bipuminbe/requests/controller/RequestsController.java
src/main/java/com/sparta/bipuminbe/requests/repository/RequestsRepository.java
src/main/java/com/sparta/bipuminbe/requests/service/RequestsService.java

feat: 요청 현황 페이지 검색어 기능 추가.

---

src/main/java/com/sparta/bipuminbe/category/repository/CategoryRepository.java
src/main/java/com/sparta/bipuminbe/requests/repository/RequestsRepository.java
src/main/java/com/sparta/bipuminbe/supply/controller/SupplyController.java
src/main/java/com/sparta/bipuminbe/supply/dto/SupplyResponseDto.java
src/main/java/com/sparta/bipuminbe/supply/repository/SupplyRepository.java
src/main/java/com/sparta/bipuminbe/supply/service/SupplyService.java

feat: 비품 관리 페이지 keyword 추가.

---

src/main/java/com/sparta/bipuminbe/category/controller/CategoryController.java
src/main/java/com/sparta/bipuminbe/category/dto/CategoryDto.java
src/main/java/com/sparta/bipuminbe/category/repository/CategoryRepository.java
src/main/java/com/sparta/bipuminbe/category/service/CategoryService.java
src/main/java/com/sparta/bipuminbe/common/entity/Category.java
src/main/java/com/sparta/bipuminbe/common/enums/LargeCategory.java

feat: 카테고리 대분류 추가.
그에 따른 코드 수정.

feat: 카테고리 대분류 추가.

---

src/main/java/com/sparta/bipuminbe/common/enums/SupplyStatusEnum.java
src/main/java/com/sparta/bipuminbe/supply/dto/SupplyResponseDto.java

fix: 비품 ResponseDto status 한국어화

fix: 비품 ResponseDto status 한국어화

---

src/main/java/com/sparta/bipuminbe/common/entity/Requests.java
src/main/java/com/sparta/bipuminbe/common/enums/AcceptResult.java
src/main/java/com/sparta/bipuminbe/common/enums/RequestType.java
src/main/java/com/sparta/bipuminbe/requests/controller/RepairRequestController.java
src/main/java/com/sparta/bipuminbe/requests/controller/RequestsController.java
src/main/java/com/sparta/bipuminbe/requests/controller/ReturnRequestController.java
src/main/java/com/sparta/bipuminbe/requests/controller/SupplyRequestController.java
src/main/java/com/sparta/bipuminbe/requests/dto/RepairRequestResponseDto.java
src/main/java/com/sparta/bipuminbe/requests/dto/RequestsResponseDto.java
src/main/java/com/sparta/bipuminbe/requests/service/RepairRequestService.java
src/main/java/com/sparta/bipuminbe/requests/service/ReturnRequestService.java
src/main/java/com/sparta/bipuminbe/requests/service/SupplyRequestService.java
src/main/java/com/sparta/bipuminbe/supply/controller/SupplyController.java

fix: 2차회의 Entity 변화 및 그에 따른 코드 수정.

fix: 2차회의 Entity 변화 및 그에 따른 코드 수정.

---

src/main/java/com/sparta/bipuminbe/common/entity/Requests.java
src/main/java/com/sparta/bipuminbe/common/exception/ErrorCode.java
src/main/java/com/sparta/bipuminbe/requests/controller/ReportRequestController.java
src/main/java/com/sparta/bipuminbe/requests/dto/ReportProcessRequestDto.java
src/main/java/com/sparta/bipuminbe/requests/dto/ReportRequestResponseDto.java
src/main/java/com/sparta/bipuminbe/requests/service/RepairRequestService.java
src/main/java/com/sparta/bipuminbe/requests/service/ReportRequestService.java
src/main/java/com/sparta/bipuminbe/requests/service/ReturnRequestService.java
src/main/java/com/sparta/bipuminbe/requests/service/SupplyRequestService.java

feat: 보고서 결재 세부 페이지 및 승인/거절 로직 구현.

feat: 보고서 결재 세부 페이지 및 승인/거절 로직 구현.

---

src/main/java/com/sparta/bipuminbe/requests/controller/RepairRequestController.java
src/main/java/com/sparta/bipuminbe/requests/dto/RepairProcessRequestDto.java
src/main/java/com/sparta/bipuminbe/requests/service/RepairRequestService.java

fix: Requests 승인/거절 RequestParam -> RequestBody로 수정중.(RepairRequest)

fix: Requests 승인/거절 RequestParam -> RequestBody로 수정중.(RepairRequest)

---

src/main/java/com/sparta/bipuminbe/requests/controller/RepairRequestController.java
src/main/java/com/sparta/bipuminbe/requests/controller/ReportRequestController.java
src/main/java/com/sparta/bipuminbe/requests/controller/RequestsController.java
src/main/java/com/sparta/bipuminbe/requests/controller/ReturnRequestController.java
src/main/java/com/sparta/bipuminbe/requests/controller/SupplyRequestController.java
src/main/java/com/sparta/bipuminbe/requests/dto/RepairProcessRequestDto.java
src/main/java/com/sparta/bipuminbe/requests/dto/RepairRequestResponseDto.java
src/main/java/com/sparta/bipuminbe/requests/dto/ReportProcessRequestDto.java
src/main/java/com/sparta/bipuminbe/requests/dto/ReportRequestResponseDto.java
src/main/java/com/sparta/bipuminbe/requests/dto/RequestsDetailsResponseDto.java
src/main/java/com/sparta/bipuminbe/requests/dto/RequestsPageResponseDto.java
src/main/java/com/sparta/bipuminbe/requests/dto/RequestsProcessRequestDto.java
src/main/java/com/sparta/bipuminbe/requests/dto/ReturnRequestResponseDto.java
src/main/java/com/sparta/bipuminbe/requests/dto/SupplyProcessRequestDto.java
src/main/java/com/sparta/bipuminbe/requests/dto/SupplyRequestResponseDto.java
src/main/java/com/sparta/bipuminbe/requests/service/RepairRequestService.java
src/main/java/com/sparta/bipuminbe/requests/service/ReportRequestService.java
src/main/java/com/sparta/bipuminbe/requests/service/RequestsService.java
src/main/java/com/sparta/bipuminbe/requests/service/ReturnRequestService.java
src/main/java/com/sparta/bipuminbe/requests/service/SupplyRequestService.java
src/main/java/com/sparta/bipuminbe/supply/service/SupplyService.java

refactor: 전체 requestType의 DetailsPage 출력 로직 합침.

refactor: 전체 requestType의 DetailsPage 출력 로직 합침.

---

src/main/java/com/sparta/bipuminbe/common/dto/SmsTo.java
src/main/java/com/sparta/bipuminbe/common/dto/SmsUtilDto.java
src/main/java/com/sparta/bipuminbe/common/util/sms/SmsUtil.java
src/main/java/com/sparta/bipuminbe/requests/controller/RequestsController.java
src/main/java/com/sparta/bipuminbe/requests/service/RequestsService.java

feat: sms 기능 연동 추가. 유료이기에 일단 주석처리.

feat: sms 기능 연동 추가.

---

src/main/java/com/sparta/bipuminbe/common/entity/Supply.java
src/main/java/com/sparta/bipuminbe/requests/dto/RequestsDetailsResponseDto.java
src/main/java/com/sparta/bipuminbe/requests/service/RequestsService.java

feat: requests의 image List화로 인한 details 페이지 수정.

feat: requests의 image List화로 인한 details 페이지 수정.

---

src/main/java/com/sparta/bipuminbe/requests/controller/RequestsController.java
src/main/java/com/sparta/bipuminbe/requests/service/RequestsService.java
src/main/java/com/sparta/bipuminbe/user/repository/UserRepository.java

feat: 유저 요청 에도 메시지 적용. 및 알람 설정에 따른 메시지 on/off

feat: 유저 요청 에도 메시지 적용. 및 알람 설정에 따른 메시지 on/off

---

src/main/java/com/sparta/bipuminbe/common/entity/Requests.java
src/main/java/com/sparta/bipuminbe/common/exception/ErrorCode.java
src/main/java/com/sparta/bipuminbe/common/exception/GlobalExceptionHandler.java
src/main/java/com/sparta/bipuminbe/requests/controller/RequestsController.java
src/main/java/com/sparta/bipuminbe/requests/dto/RequestsRequestDto.java
src/main/java/com/sparta/bipuminbe/requests/repository/RequestsRepository.java
src/main/java/com/sparta/bipuminbe/requests/service/RequestsService.java
src/main/java/com/sparta/bipuminbe/supply/service/SupplyService.java

feat: 유저 페이지도 생각해서 로직 수정 및 추가.

feat: 유저 페이지도 생각해서 로직 수정 및 추가.

---

.gitignore
src/main/java/com/sparta/bipuminbe/common/entity/Supply.java
src/main/java/com/sparta/bipuminbe/supply/controller/SupplyController.java
src/main/java/com/sparta/bipuminbe/supply/dto/SupplyDetailResponseDto.java
src/main/java/com/sparta/bipuminbe/supply/dto/SupplyRepairHistoryResponseDto.java
src/main/java/com/sparta/bipuminbe/supply/dto/SupplyRequestDto.java
src/main/java/com/sparta/bipuminbe/supply/dto/SupplyResponseDto.java
src/main/java/com/sparta/bipuminbe/supply/dto/SupplyWholeResponseDto.java
src/main/java/com/sparta/bipuminbe/supply/service/SupplyService.java

feat : 비품등록 이미지 추가 및 비품상세 수정

---

src/main/java/com/sparta/bipuminbe/common/entity/Supply.java
src/main/java/com/sparta/bipuminbe/requests/controller/RequestsController.java
src/main/java/com/sparta/bipuminbe/requests/dto/RequestsProcessRequestDto.java
src/main/java/com/sparta/bipuminbe/requests/dto/RequestsRequestDto.java
src/main/java/com/sparta/bipuminbe/requests/service/RequestsService.java
src/main/java/com/sparta/bipuminbe/supply/controller/SupplyController.java
src/main/java/com/sparta/bipuminbe/supply/dto/StockListResponseDto.java
src/main/java/com/sparta/bipuminbe/supply/dto/SupplyResponseDto.java
src/main/java/com/sparta/bipuminbe/supply/service/SupplyService.java

feat: 현황 조회 페이지들, Sort Request Param "ALL"을 ""로 통일화. feat: User 재고현황 페이지 구현.

feat: 현황 조회 페이지들, Sort Request Param "ALL"을 ""로 통일화. feat: User 재고현황 페이지 구현.

---

src/main/java/com/sparta/bipuminbe/supply/service/SupplyService.java

feat: 비품 상세 페이지 출력할 때 사용/수리 history 1페이지 함께 출력하도록.

feat: 비품 상세 페이지 출력할 때 사용/수리 history 1페이지 함께 출력하도록.

---

src/main/java/com/sparta/bipuminbe/category/repository/CategoryRepository.java
src/main/java/com/sparta/bipuminbe/supply/service/SupplyService.java

fix: 비품 수정 로직 수정.

---

src/main/java/com/sparta/bipuminbe/common/entity/Partners.java
src/main/java/com/sparta/bipuminbe/common/entity/Requests.java
src/main/java/com/sparta/bipuminbe/common/entity/Supply.java
src/main/java/com/sparta/bipuminbe/common/entity/User.java
src/main/java/com/sparta/bipuminbe/common/exception/ErrorCode.java
src/main/java/com/sparta/bipuminbe/partners/repository/PartnersRepository.java
src/main/java/com/sparta/bipuminbe/partners/service/PartnersService.java
src/main/java/com/sparta/bipuminbe/requests/repository/RequestsRepository.java
src/main/java/com/sparta/bipuminbe/requests/service/RequestsService.java
src/main/java/com/sparta/bipuminbe/supply/dto/SupplyRequestDto.java
src/main/java/com/sparta/bipuminbe/supply/repository/SupplyRepository.java
src/main/java/com/sparta/bipuminbe/supply/service/SupplyService.java
src/main/java/com/sparta/bipuminbe/user/repository/UserRepository.java

feat: Supply SoftDelete 적용.

---

src/main/java/com/sparta/bipuminbe/supply/dto/SupplyHistoryResponseDto.java

fix: 비품 상세 페이지. history dto 수정.

fix: 비품 상세 페이지. history dto 수정.

---

src/main/java/com/sparta/bipuminbe/supply/dto/SupplyDetailResponseDto.java

feat: Supply details 페이지 dto 필드 추가.

feat: Supply details 페이지 dto 필드 추가.

---

src/main/java/com/sparta/bipuminbe/supply/controller/SupplyController.java

fix: 비품 수정 데이터 형태 수정.

---

src/main/java/com/sparta/bipuminbe/supply/controller/SupplyController.java

fix: 비품 수정 데이터 형태 수정. ModelAttribute

fix: 비품 수정 데이터 형태 수정. ModelAttribute

---

src/main/java/com/sparta/bipuminbe/common/entity/Requests.java
src/main/java/com/sparta/bipuminbe/requests/controller/RequestsController.java
src/main/java/com/sparta/bipuminbe/requests/service/RequestsService.java
src/main/java/com/sparta/bipuminbe/supply/controller/SupplyController.java
src/main/java/com/sparta/bipuminbe/supply/dto/SupplyDetailResponseDto.java
src/main/java/com/sparta/bipuminbe/supply/service/SupplyService.java

fix: 비품 상세 조회 ADMIN 페이지 분리.

---

src/main/java/com/sparta/bipuminbe/supply/controller/SupplyController.java

style: Swagger 문서 설명 상세화

---

src/main/java/com/sparta/bipuminbe/supply/controller/SupplyController.java
src/main/java/com/sparta/bipuminbe/supply/dto/SupplyDetailResponseDto.java
src/main/java/com/sparta/bipuminbe/supply/service/SupplyService.java

feat: 비품 상세 페이지에 isMySupply 추가. (버튼 구현하기 위함.)

feat: 비품 상세 페이지에 isMySupply 추가. (버튼 구현하기 위함.)

---

src/main/java/com/sparta/bipuminbe/common/entity/Requests.java
src/main/java/com/sparta/bipuminbe/requests/controller/RequestsController.java
src/main/java/com/sparta/bipuminbe/requests/dto/RequestsPageResponseDto.java
src/main/java/com/sparta/bipuminbe/requests/service/RequestsService.java
src/main/java/com/sparta/bipuminbe/supply/controller/SupplyController.java
src/main/java/com/sparta/bipuminbe/supply/service/SupplyService.java

feat: 요청서(requests) entity admin(담당자) 필드 추가. 그에 따른 로직 수정.

feat: 요청서(requests) entity admin(담당자) 필드 추가. 그에 따른 로직 수정.

---

src/main/java/com/sparta/bipuminbe/requests/controller/RequestsController.java
src/main/java/com/sparta/bipuminbe/requests/dto/RequestsAdminDetailsResponseDto.java
src/main/java/com/sparta/bipuminbe/requests/service/RequestsService.java

feat: 요청 상세 페이지 (User) 구현.

---

src/main/java/com/sparta/bipuminbe/supply/controller/SupplyController.java
src/main/java/com/sparta/bipuminbe/supply/repository/SupplyRepository.java
src/main/java/com/sparta/bipuminbe/supply/service/SupplyService.java

feat: 자신의 비품 목록 조회, categoryId Pathvariable 추가.

feat: 자신의 비품 목록 조회, categoryId Pathvariable 추가.

---

src/main/java/com/sparta/bipuminbe/common/entity/Partners.java
src/main/java/com/sparta/bipuminbe/common/entity/User.java
src/main/java/com/sparta/bipuminbe/common/sse/service/NotificationService.java
src/main/java/com/sparta/bipuminbe/requests/controller/RequestsController.java
src/main/java/com/sparta/bipuminbe/requests/dto/RequestsAdminDetailsResponseDto.java
src/main/java/com/sparta/bipuminbe/requests/service/RequestsService.java
src/main/java/com/sparta/bipuminbe/supply/repository/SupplyRepository.java
src/main/java/com/sparta/bipuminbe/supply/service/SupplyService.java
src/main/java/com/sparta/bipuminbe/user/controller/UserController.java
src/main/java/com/sparta/bipuminbe/user/repository/UserRepository.java
src/main/java/com/sparta/bipuminbe/user/service/UserService.java

feat: user Soft Delete 적용.

---

src/main/java/com/sparta/bipuminbe/category/controller/CategoryController.java
src/main/java/com/sparta/bipuminbe/category/dto/CategoryDto.java
src/main/java/com/sparta/bipuminbe/category/repository/CategoryRepository.java
src/main/java/com/sparta/bipuminbe/category/service/CategoryService.java
src/main/java/com/sparta/bipuminbe/common/entity/Category.java
src/main/java/com/sparta/bipuminbe/dashboard/dto/SupplyCountDto.java
src/main/java/com/sparta/bipuminbe/supply/repository/SupplyRepository.java

feat: 유저 요청 페이지,selectBox용 myLargeCateogry, largeCategory

feat: 유저 요청 페이지,selectBox용 myLargeCateogry, largeCategory

---

src/main/java/com/sparta/bipuminbe/common/entity/Category.java
src/main/java/com/sparta/bipuminbe/common/entity/Supply.java
src/main/java/com/sparta/bipuminbe/user/controller/UserController.java
src/main/java/com/sparta/bipuminbe/user/service/UserService.java

fix: UserService 오류 수정.

---

build.gradle
src/main/java/com/sparta/bipuminbe/partners/repository/PartnersRepository.java
src/main/java/com/sparta/bipuminbe/supply/controller/SupplyController.java
src/main/java/com/sparta/bipuminbe/supply/dto/ExcelCoverDto.java
src/main/java/com/sparta/bipuminbe/supply/dto/SupplyExcelDto.java
src/main/java/com/sparta/bipuminbe/supply/service/SupplyService.java
src/main/java/com/sparta/bipuminbe/user/repository/UserRepository.java

feat : 비품 복수 등록 추가

---

src/main/java/com/sparta/bipuminbe/common/entity/User.java
src/main/java/com/sparta/bipuminbe/supply/controller/SupplyController.java
src/main/java/com/sparta/bipuminbe/supply/repository/SupplyRepository.java
src/main/java/com/sparta/bipuminbe/supply/service/SupplyService.java

feat: 자신의 부서의 공용 비품 목록 조회 api.

feat: 자신의 부서의 공용 비품 목록 조회 api.

---

src/main/java/com/sparta/bipuminbe/common/entity/Supply.java
src/main/java/com/sparta/bipuminbe/common/entity/TimeStamped.java
src/main/java/com/sparta/bipuminbe/common/exception/ErrorCode.java
src/main/java/com/sparta/bipuminbe/requests/dto/RequestsAdminDetailsResponseDto.java
src/main/java/com/sparta/bipuminbe/requests/dto/RequestsDetailsResponseDto.java
src/main/java/com/sparta/bipuminbe/requests/dto/RequestsPageResponseDto.java
src/main/java/com/sparta/bipuminbe/supply/controller/SupplyController.java
src/main/java/com/sparta/bipuminbe/supply/dto/ExcelCoverDto.java
src/main/java/com/sparta/bipuminbe/supply/dto/SupplyExcelDto.java
src/main/java/com/sparta/bipuminbe/supply/service/SupplyService.java

fix: 카테고리 삭제되었을 시 Supply Requests 관련 오류.

fix: 카테고리 삭제되었을 시 Supply Requests 관련 오류.

---

src/main/java/com/sparta/bipuminbe/common/exception/ErrorCode.java
src/main/java/com/sparta/bipuminbe/common/s3/S3Uploader.java
src/main/java/com/sparta/bipuminbe/supply/controller/SupplyController.java
src/main/java/com/sparta/bipuminbe/supply/dto/ExcelCoverDto.java
src/main/java/com/sparta/bipuminbe/supply/dto/SupplyExcelDto.java
src/main/java/com/sparta/bipuminbe/supply/service/SupplyService.java

feat : 복수등록 try1 , Json.stringify해서 객체 묶어서 받기.

feat : 복수등록 try1 

---

src/main/java/com/sparta/bipuminbe/supply/dto/SupplyExcelDto.java
src/main/java/com/sparta/bipuminbe/supply/repository/SupplyRepository.java
src/main/java/com/sparta/bipuminbe/supply/service/SupplyService.java

fix: 요청 페이지. 공용 비품 목록 요청가능한 목록만 뜨도록 로직 수정.

fix: 요청 페이지. 공용 비품 목록 요청가능한 목록만 뜨도록 로직 수정.

---

src/main/java/com/sparta/bipuminbe/supply/controller/SupplyController.java
src/main/java/com/sparta/bipuminbe/supply/service/SupplyService.java

fix: 비품 이미지 naver Search. 비품 복수 등록도 가능하도록 param list화.

fix: 비품 이미지 naver Search. 비품 복수 등록도 가능하도록 param list화.

---

src/main/java/com/sparta/bipuminbe/category/repository/CategoryRepository.java
src/main/java/com/sparta/bipuminbe/category/service/CategoryService.java
src/main/java/com/sparta/bipuminbe/common/entity/Category.java
src/main/java/com/sparta/bipuminbe/common/entity/Requests.java
src/main/java/com/sparta/bipuminbe/common/setting/service/SettingService.java
src/main/java/com/sparta/bipuminbe/dashboard/service/DashboardService.java
src/main/java/com/sparta/bipuminbe/requests/repository/RequestsRepository.java
src/main/java/com/sparta/bipuminbe/supply/repository/SupplyRepository.java
src/main/java/com/sparta/bipuminbe/supply/service/SupplyService.java

fix: 카테고리 softDelete 적용.

---

src/main/java/com/sparta/bipuminbe/supply/service/SupplyService.java

fix: 이미지 빈string 들어갈때 이미지 빈값으로 저장되는 현상 수정.

fix: 이미지 빈string 들어갈때 이미지 빈값으로 저장되는 현상 수정.

---

src/main/java/com/sparta/bipuminbe/supply/dto/SupplyExcelDto.java
src/main/java/com/sparta/bipuminbe/supply/service/SupplyService.java

fix: 복수등록. user, partners 에러 해결 try1

fix: 복수등록. user, partners 에러 해결 try1

---

src/main/java/com/sparta/bipuminbe/requests/dto/RequestsAdminDetailsResponseDto.java
src/main/java/com/sparta/bipuminbe/supply/service/SupplyService.java

fix: 요청 상세 페이지 Dto phone 추가.

---

src/main/java/com/sparta/bipuminbe/department/repository/DepartmentRepository.java
src/main/java/com/sparta/bipuminbe/supply/controller/SupplyController.java
src/main/java/com/sparta/bipuminbe/supply/service/SupplyService.java

fix: 복수등록 이제 진짜 되지 않을까?

---

src/main/java/com/sparta/bipuminbe/common/exception/ErrorCode.java
src/main/java/com/sparta/bipuminbe/supply/service/SupplyService.java

fix: createdAt CustomException 추가.

fix: createdAt CustomException 추가.

---

src/main/java/com/sparta/bipuminbe/supply/service/SupplyService.java

fix: createdAt LocalDateTime 형식 오류 해결.

fix: createdAt LocalDateTime 형식 오류 해결.

---

src/main/java/com/sparta/bipuminbe/supply/service/SupplyService.java

fix: image 수량 match 로직 수정.

---

src/main/java/com/sparta/bipuminbe/supply/service/SupplyService.java

fix: 오류 문구 오해의 소지가 있어 순서 변경.

---

src/main/java/com/sparta/bipuminbe/supply/service/SupplyService.java

fix: 복수등록 공용 비품 관련 로직 수정.

---

src/main/java/com/sparta/bipuminbe/dashboard/controller/DashboardController.java
src/main/java/com/sparta/bipuminbe/dashboard/dto/RequestsSearchDto.java
src/main/java/com/sparta/bipuminbe/dashboard/dto/SearchTotalDto.java
src/main/java/com/sparta/bipuminbe/dashboard/dto/SupplySearchDto.java
src/main/java/com/sparta/bipuminbe/requests/dto/RequestsAdminDetailsResponseDto.java
src/main/java/com/sparta/bipuminbe/requests/dto/RequestsDetailsResponseDto.java

fix: 재고 비품 폐기 처리 시 나오는 오류 수정.

---

src/main/java/com/sparta/bipuminbe/requests/dto/RequestsDetailsResponseDto.java

fix: 유저 페이지 비품 요청 처리전 상세페이지 오류 수정.

fix: 유저 페이지 비품 요청 처리전 상세페이지 오류 수정.

---

src/main/java/com/sparta/bipuminbe/requests/dto/RequestsDetailsResponseDto.java

fix : 요청 상세 페이지 오류 수정.

---

src/main/java/com/sparta/bipuminbe/supply/controller/SupplyController.java
src/main/java/com/sparta/bipuminbe/supply/service/SupplyService.java

fix : naver api 서치 속도 제어.

---

src/main/java/com/sparta/bipuminbe/common/exception/ErrorCode.java
src/main/java/com/sparta/bipuminbe/supply/service/SupplyService.java

fix : 엑셀 등록 2개 이상만 가능하도록 ExcelAmountLessThanTwo 에러 추가.

fix : 엑셀 등록 2개 이상만 가능하도록 ExcelAmountLessThanTwo 에러 추가.

---

src/main/java/com/sparta/bipuminbe/common/entity/User.java
src/main/java/com/sparta/bipuminbe/common/exception/ErrorCode.java
src/main/java/com/sparta/bipuminbe/supply/repository/SupplyRepository.java
src/main/java/com/sparta/bipuminbe/supply/service/SupplyService.java

fix : serialNumber 체크. Validation 추가.

fix : serialNumber 체크. Validation 추가.

---

src/main/java/com/sparta/bipuminbe/supply/dto/SupplyDetailResponseDto.java

fix : 비품 상세 페이지 deptId 필드 추가.

---

src/main/java/com/sparta/bipuminbe/common/entity/User.java
src/main/java/com/sparta/bipuminbe/user/controller/UserController.java
src/main/java/com/sparta/bipuminbe/user/dto/UserInfoResponseDto.java
src/main/java/com/sparta/bipuminbe/user/dto/UserUpdateRequestDto.java
src/main/java/com/sparta/bipuminbe/user/service/UserService.java

fix : 유저 정보 수정 이미지 추가 및 오류 수정.

fix : 유저 정보 수정 이미지 추가 및 오류 수정.

---

appspec.yml

chore : appspec 파일 run as ubuntu -> root로 수정. (자동배포시 이미지 업로드 Permission)

chore : appspec 파일 run as ubuntu -> root로 수정. (자동배포시 이미지 업로드 Permission)

---

build.gradle
docker-compose.yml
src/main/java/com/sparta/bipuminbe/common/config/SwaggerConfig.java
src/main/java/com/sparta/bipuminbe/common/config/WebSecurityConfig.java
src/main/java/com/sparta/bipuminbe/common/entity/Notification.java
src/main/java/com/sparta/bipuminbe/common/enums/TokenType.java
src/main/java/com/sparta/bipuminbe/common/exception/ErrorCode.java
src/main/java/com/sparta/bipuminbe/common/jwt/JwtAuthFilter.java
src/main/java/com/sparta/bipuminbe/common/jwt/JwtUtil.java
src/main/java/com/sparta/bipuminbe/common/sse/contoller/NotificationController.java
src/main/java/com/sparta/bipuminbe/common/sse/repository/NotificationRepository.java
src/main/java/com/sparta/bipuminbe/common/sse/service/NotificationService.java
src/main/java/com/sparta/bipuminbe/common/util/redis/RedisConfig.java
src/main/java/com/sparta/bipuminbe/common/util/redis/RedisRepository.java
src/main/java/com/sparta/bipuminbe/common/util/redis/RefreshToken.java
src/main/java/com/sparta/bipuminbe/user/controller/UserController.java
src/main/java/com/sparta/bipuminbe/user/service/UserService.java

feat: RefreshToken 기능 추가. Redis 사용. 
chore: Redis Build 추가. 
fix: Security PermitAll 해제. 
fix: Swagger RefreshToken 추가.
feat: 알람 전체 삭제 기능 추가.
feat: 유저 관리(삭제) 완료.

Refresh 및 잡다한 것들

---

src/main/java/com/sparta/bipuminbe/user/controller/UserController.java
src/main/java/com/sparta/bipuminbe/user/dto/UserUpdateRequestDto.java
src/main/java/com/sparta/bipuminbe/user/service/UserService.java

feat: user 정보 수정 password 변경 추가.

feat: user 정보 수정 password 변경 추가.

---

src/main/java/com/sparta/bipuminbe/common/enums/TokenState.java
src/main/java/com/sparta/bipuminbe/common/jwt/JwtAuthFilter.java
src/main/java/com/sparta/bipuminbe/common/jwt/JwtUtil.java

feat: refreshToken exception Handler 수정.

feat: refreshToken exception Handler 수정.

---

src/main/java/com/sparta/bipuminbe/user/controller/UserController.java
src/main/java/com/sparta/bipuminbe/user/service/UserService.java

fix: Ip front를 통해 받아오던 것을, header에서 추출하는 방식으로 변경.

fix: Ip front를 통해 받아오던 것을, header에서 추출하는 방식으로 변경.

---

src/main/java/com/sparta/bipuminbe/common/jwt/JwtUtil.java
src/main/java/com/sparta/bipuminbe/user/controller/UserController.java
src/main/java/com/sparta/bipuminbe/user/dto/AccessTokenDto.java
src/main/java/com/sparta/bipuminbe/user/dto/LoginRequestDto.java
src/main/java/com/sparta/bipuminbe/user/dto/UserUpdateRequestDto.java
src/main/java/com/sparta/bipuminbe/user/service/UserService.java

fix: RefreshToken 점검을 위해 시간 축소. 잠시 구글 리프레쉬 토큰 수집 멈춤.

fix: RefreshToken 점검을 위해 시간 축소. 잠시 구글 리프레쉬 토큰 수집 멈춤.

---

src/main/java/com/sparta/bipuminbe/dashboard/controller/DashboardController.java
src/main/java/com/sparta/bipuminbe/dashboard/dto/RequestsSearchDto.java
src/main/java/com/sparta/bipuminbe/dashboard/dto/SearchTotalDto.java
src/main/java/com/sparta/bipuminbe/dashboard/dto/SupplySearchDto.java
src/main/java/com/sparta/bipuminbe/dashboard/service/DashboardService.java
src/main/java/com/sparta/bipuminbe/requests/repository/RequestsRepository.java
src/main/java/com/sparta/bipuminbe/requests/service/RequestsService.java
src/main/java/com/sparta/bipuminbe/supply/repository/SupplyRepository.java
src/main/java/com/sparta/bipuminbe/supply/service/SupplyService.java

feat: Admin/User 대시보드 상단 검색 구현.

feat: Admin/User 대시보드 상단 검색 구현.

---

src/main/java/com/sparta/bipuminbe/common/sse/repository/NotificationRepository.java
src/main/java/com/sparta/bipuminbe/requests/service/RequestsService.java

fix : Requests를 삭제할 때, 알림도 삭제하도록 구현.

fix : Requests를 삭제할 때, 알림도 삭제하도록 구현.

---

src/main/java/com/sparta/bipuminbe/common/config/WebSecurityConfig.java
src/main/java/com/sparta/bipuminbe/common/entity/Department.java
src/main/java/com/sparta/bipuminbe/common/entity/User.java
src/main/java/com/sparta/bipuminbe/common/enums/UserRoleEnum.java
src/main/java/com/sparta/bipuminbe/common/exception/ErrorCode.java
src/main/java/com/sparta/bipuminbe/department/controller/DepartmentController.java
src/main/java/com/sparta/bipuminbe/department/dto/DeptByEmployeeDto.java
src/main/java/com/sparta/bipuminbe/department/service/DepartmentService.java
src/main/java/com/sparta/bipuminbe/supply/dto/SupplyDetailResponseDto.java
src/main/java/com/sparta/bipuminbe/user/controller/UserController.java
src/main/java/com/sparta/bipuminbe/user/dto/MasterLoginRequestDto.java
src/main/java/com/sparta/bipuminbe/user/repository/UserRepository.java
src/main/java/com/sparta/bipuminbe/user/service/UserService.java

feat: Master 로그인 로직 완료. feat: Master 최초 로그인시 부서 초기 세팅 로직 완료.

feat: Master 로그인 로직 완료. feat: Master 최초 로그인시 부서 초기 세팅 로직 완료.

---

src/main/java/com/sparta/bipuminbe/department/controller/DepartmentController.java
src/main/java/com/sparta/bipuminbe/department/dto/DefaultDeptRequestDto.java
src/main/java/com/sparta/bipuminbe/department/service/DepartmentService.java

fix: dept List 받는 Dto 변경.

---

src/main/java/com/sparta/bipuminbe/common/enums/UserRoleEnum.java

fix: Authority 변경

---

src/main/java/com/sparta/bipuminbe/user/controller/UserController.java
src/main/java/com/sparta/bipuminbe/user/dto/MasterLoginResponseDto.java
src/main/java/com/sparta/bipuminbe/user/service/UserService.java

fix: Master Login ResponseDto로 변경.

fix: Master Login ResponseDto로 변경.

---

src/main/java/com/sparta/bipuminbe/user/dto/MasterLoginResponseDto.java

fix: Master Login ResponseDto 필드 오류 수정.

fix: Master Login ResponseDto 필드 오류 수정.

---

src/main/java/com/sparta/bipuminbe/common/enums/Company.java
src/main/java/com/sparta/bipuminbe/department/controller/DepartmentController.java
src/main/java/com/sparta/bipuminbe/user/controller/UserController.java
src/main/java/com/sparta/bipuminbe/user/dto/UserInfoResponseDto.java

fix: Master 계정 상단 헤더 정보 추가.

---

src/main/java/com/sparta/bipuminbe/common/sse/contoller/NotificationController.java
src/main/java/com/sparta/bipuminbe/common/sse/repository/NotificationRepository.java
src/main/java/com/sparta/bipuminbe/common/sse/service/NotificationService.java

fix: 알림 삭제 기능. 유저모드/Admin 모드 개별 삭제 구현.

fix: 알림 삭제 기능. 유저모드/Admin 모드 개별 삭제 구현.

---

src/main/java/com/sparta/bipuminbe/common/sse/contoller/NotificationController.java
src/main/java/com/sparta/bipuminbe/common/sse/dto/NotificationCountResponseDto.java
src/main/java/com/sparta/bipuminbe/common/sse/service/NotificationService.java

fix: 알림 count User/Admin 한번에 반환하도록 구현.

fix: 알림 count User/Admin 한번에 반환하도록 구현.

---

src/main/java/com/sparta/bipuminbe/common/jwt/JwtAuthFilter.java
src/main/java/com/sparta/bipuminbe/user/service/UserService.java

fix: Jwt Token Cookie 삭제 value "" -> null

fix: Jwt Token Cookie 삭제 value "" -> null

---

src/main/java/com/sparta/bipuminbe/common/jwt/JwtAuthFilter.java

fix: Jwt Token Cookie 삭제 로직 jwtAuthFilter에 추가.

fix: Jwt Token Cookie 삭제 로직 jwtAuthFilter에 추가.

---

src/main/java/com/sparta/bipuminbe/department/controller/DepartmentController.java
src/main/java/com/sparta/bipuminbe/department/dto/DeptByEmployeeDto.java
src/main/java/com/sparta/bipuminbe/department/service/DepartmentService.java
src/main/java/com/sparta/bipuminbe/user/repository/UserRepository.java

feat: 부서 및 권한 설정 페이지, 검색 기능 추가.

feat: 부서 및 권한 설정 페이지, 검색 기능 추가.

---

src/main/java/com/sparta/bipuminbe/common/sse/service/NotificationService.java
src/main/java/com/sparta/bipuminbe/supply/repository/SupplyRepository.java
src/main/java/com/sparta/bipuminbe/user/repository/UserRepository.java

fix: 알림 카운트 초기화. transactional read only 해제.

fix: 알림 카운트 초기화. transactional read only 해제.

---

README.md

README 재수정

---

README.md

README 재수정(2)

---

README.md

README 재수정(4)
